#parameters:
#    parameter_name: value

services:
  customFieldProvider:
    class:  TestForge\Syrphus\CustomFieldBundle\Services\CustomFieldProviderService
    arguments: ['@doctrine.orm.entity_manager']