<?php

namespace TestForge\Syrphus\CustomFieldBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomFieldTypeOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldTypeOptionRepository extends EntityRepository
{
}