<?php

namespace TestForge\Syrphus\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    const ROLE_DEFAULT_NAME = "user";
    const ROLE_ROOT_NAME = "root";

    public function getDefaultRole()
    {
        return $this->getRoleByName(self::ROLE_DEFAULT_NAME);
    }

    public function getRoleByName($name)
    {
        return $this->findOneBy(["name" => $name]);
    }
}
