<?php

namespace TestForge\Syrphus\SecurityBundle\Repository;

/**
 * UserLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
